### ISSUE TITLE
Error trying to run your code on terminal 

### ISSUE THREAD

**Issue by vij21** [sevetseh28/instagram-unfollowers-unfollowing#3]
I'm having issue trying to run your code on terminal. I pasted my instagram string (it was really long) then when I ran it prints out the entire string on terminal and this message at the end of it "must be of type str or bytes, not <class 'list'>" 

Do I need to put it like this? 

COOKIE = ' My long instagram string inside ' 
do I need to include " ' ' " this?

thank you

**Comment by sevetseh28** [comment]
Yes, the COOKIE setting should be a string. Check that it was escaped correctly and that the whole value is a string, you may have quotes inside.
